# Default initial positions for ARV_V1_MODEL's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 2.1746
  joint_3: -0.937
  joint_4: -1.3226
  joint_5: 1.5028
  joint_6: -1.6796
  joint_gripper1: 0.0  # 夹爪初始位置（米），0=夹爪张开