# Default initial positions for ARV_V1_MODEL's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  joint_gripper1: 0.0  # 夹爪初始位置（米），0=夹爪收起