# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ARM_controller  # 指向你的自定义控制器的 action namespace

  ARM_controller:  # 你的 TorqueControllerActionServer 需要提供这个 action
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory  # 完整路径: /ARM_controller/follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

trajectory_execution:
  allowed_start_tolerance: 0.4 # 误差大约40度